name: Daily Auto Commit

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 5:30 AM UTC (change as needed)
  workflow_dispatch:  # Allows manual execution

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git (21f3001176@ds.study.iitm.ac.in)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "21f3001176@ds.study.iitm.ac.in"

      - name: Make a change (21f3001176@ds.study.iitm.ac.in)
        run: |
          echo "Last updated on $(date)" > update_log.txt

      - name: Commit and push changes (21f3001176@ds.study.iitm.ac.in)
        run: |
          git add update_log.txt
          git commit -m "Automated commit: $(date)"
          git push
